region           = "us-east-1" # Replace with your desired AWS region
vpc_id           = "vpc-37d6a34a" # Replace with your VPC ID
subnet_id        = "subnet-1abd9a3b" # Replace with your Subnet ID
key_name         = "linuxmgm01" # Replace with your key pair name
ami_id           = "ami-04c9d7e18b307fef6" # Replace with your desired AMI ID
instance_type    = "t2.micro" # Replace with your desired instance type
disk_size        = 30 # Replace with the desired OS disk size in GB
disk_type        = "standard" # Replace with your desired disk type (gp2, io1, io2, sc1, st1)
security_group_id = "sg-0e5d8828a0c3c205b" # Replace with your security group ID
instance_name    = "symphony-demo-new"