resource_group_name = "$var.rg"
vm_name             = "$var.vm"
vm_size             = "$var.target_size"   
nic_name            = "$var.nic_name"
os_disk_id          = "$var.os_disk_id"
os_disk_name        = "$var.os_disk_name"
